set_property SRC_FILE_INFO {cfile:C:/Git/slime/hdmi-out.srcs/constrs_1/imports/constraints/ZYBO_Master.xdc rfile:../../../hdmi-out.srcs/constrs_1/imports/constraints/ZYBO_Master.xdc id:1} [current_design]
set_property src_info {type:XDC file:1 line:112 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN H16 [get_ports TMDS_clk_p]
set_property src_info {type:XDC file:1 line:119 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN D19 [get_ports {TMDS_data_p[0]}]
set_property src_info {type:XDC file:1 line:126 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN C20 [get_ports {TMDS_data_p[1]}]
set_property src_info {type:XDC file:1 line:133 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN B19 [get_ports {TMDS_data_p[2]}]
set_property src_info {type:XDC file:1 line:142 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN F17 [get_ports {HDMI_OEN[0]}]
set_property src_info {type:XDC file:1 line:400 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS33 [get_ports {gpio_rtl_tri_i[7]}]
set_property src_info {type:XDC file:1 line:401 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS33 [get_ports {gpio_rtl_tri_i[6]}]
set_property src_info {type:XDC file:1 line:402 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS33 [get_ports {gpio_rtl_tri_i[5]}]
set_property src_info {type:XDC file:1 line:403 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS33 [get_ports {gpio_rtl_tri_i[4]}]
set_property src_info {type:XDC file:1 line:408 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN V12 [get_ports {gpio_rtl_tri_i[7]}]
set_property src_info {type:XDC file:1 line:409 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN W16 [get_ports {gpio_rtl_tri_i[6]}]
set_property src_info {type:XDC file:1 line:410 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN J15 [get_ports {gpio_rtl_tri_i[5]}]
set_property src_info {type:XDC file:1 line:411 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN H15 [get_ports {gpio_rtl_tri_i[4]}]
set_property src_info {type:XDC file:1 line:413 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN E18 [get_ports {HDMI_HPD_tri_i[0]}]
set_property src_info {type:XDC file:1 line:415 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN G17 [get_ports HDMI_DDC_scl_io]
set_property src_info {type:XDC file:1 line:416 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN G18 [get_ports HDMI_DDC_sda_io]
set_property src_info {type:XDC file:1 line:417 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN N18 [get_ports IIC_0_scl_io]
set_property src_info {type:XDC file:1 line:418 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN N17 [get_ports IIC_0_sda_io]
set_property src_info {type:XDC file:1 line:424 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN V13 [get_ports {gpio_rtl_0_tri_i[3]}]
set_property src_info {type:XDC file:1 line:425 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN U17 [get_ports {gpio_rtl_0_tri_i[2]}]
set_property src_info {type:XDC file:1 line:426 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN T17 [get_ports {gpio_rtl_0_tri_i[1]}]
set_property src_info {type:XDC file:1 line:427 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN Y17 [get_ports {gpio_rtl_0_tri_i[0]}]
set_property src_info {type:XDC file:1 line:428 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN V12 [get_ports {gpio_rtl_tri_i[3]}]
set_property src_info {type:XDC file:1 line:429 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN W16 [get_ports {gpio_rtl_tri_i[2]}]
set_property src_info {type:XDC file:1 line:430 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN J15 [get_ports {gpio_rtl_tri_i[1]}]
set_property src_info {type:XDC file:1 line:431 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN H15 [get_ports {gpio_rtl_tri_i[0]}]
