# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Git/slime/hdmi-out.srcs/sources_1/bd/hdmi_out/ip/hdmi_out_axi_gpio_0_1/hdmi_out_axi_gpio_0_1.xci
# IP: The module: 'hdmi_out_axi_gpio_0_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Git/slime/hdmi-out.srcs/sources_1/bd/hdmi_out/ip/hdmi_out_axi_gpio_0_1/hdmi_out_axi_gpio_0_1_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'hdmi_out_axi_gpio_0_1'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: c:/Git/slime/hdmi-out.srcs/sources_1/bd/hdmi_out/ip/hdmi_out_axi_gpio_0_1/hdmi_out_axi_gpio_0_1_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'hdmi_out_axi_gpio_0_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: c:/Git/slime/hdmi-out.srcs/sources_1/bd/hdmi_out/ip/hdmi_out_axi_gpio_0_1/hdmi_out_axi_gpio_0_1.xdc
# XDC: The top module name and the constraint reference have the same name: 'hdmi_out_axi_gpio_0_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: c:/Git/slime/hdmi-out.srcs/sources_1/bd/hdmi_out/ip/hdmi_out_axi_gpio_0_1/hdmi_out_axi_gpio_0_1.xci
# IP: The module: 'hdmi_out_axi_gpio_0_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Git/slime/hdmi-out.srcs/sources_1/bd/hdmi_out/ip/hdmi_out_axi_gpio_0_1/hdmi_out_axi_gpio_0_1_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'hdmi_out_axi_gpio_0_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: c:/Git/slime/hdmi-out.srcs/sources_1/bd/hdmi_out/ip/hdmi_out_axi_gpio_0_1/hdmi_out_axi_gpio_0_1_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'hdmi_out_axi_gpio_0_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: c:/Git/slime/hdmi-out.srcs/sources_1/bd/hdmi_out/ip/hdmi_out_axi_gpio_0_1/hdmi_out_axi_gpio_0_1.xdc
# XDC: The top module name and the constraint reference have the same name: 'hdmi_out_axi_gpio_0_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
